create table public.profile (
  id bigint generated by default as identity primary key,
  name text not null,
  title text,
  affiliation text,
  bio text,
  research_interests text,
  email text,
  location text,
  profile_image_url text,
  orcid text,
  google_scholar text,
  researchgate text,
  github text,
  linkedin text,
  cv_url text,
  updated_at timestamptz not null default now()
);

alter table public.profile enable row level security;

create policy "Public can read profile"
on public.profile
for select
to anon, authenticated
using (true);

create policy "Authenticated users can insert profile"
on public.profile
for insert
to authenticated
with check (true);

create policy "Authenticated users can update profile"
on public.profile
for update
to authenticated
using (true)
with check (true);

create policy "Authenticated users can delete profile"
on public.profile
for delete
to authenticated
using (true);