create table public.publications (
  id bigint generated by default as identity primary key,
  title text not null,
  authors text,
  journal text,
  year integer,
  doi text,
  abstract text,
  url text,
  featured boolean not null default false,
  published boolean not null default true,
  created_at timestamptz not null default now()
);

alter table public.publications enable row level security;

create policy "Public can read published publications"
on public.publications
for select
to anon, authenticated
using (published = true);
