create table public.software_data (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  type text,
  category text,
  url text,
  github_url text,
  documentation_url text,
  image_url text,
  year integer,
  featured boolean not null default false,
  published boolean not null default true,
  created_at timestamptz not null default now()
);

alter table public.software_data enable row level security;

create policy "Public can read published software and data"
on public.software_data
for select
to anon, authenticated
using (published = true);

create policy "Authenticated users can insert software and data"
on public.software_data
for insert
to authenticated
with check (true);

create policy "Authenticated users can update software and data"
on public.software_data
for update
to authenticated
using (true)
with check (true);

create policy "Authenticated users can delete software and data"
on public.software_data
for delete
to authenticated
using (true);
