create table public.cv (
  id bigint generated by default as identity primary key,
  name text not null,
  title text,
  affiliation text,
  summary text,
  education text,
  experience text,
  research_interests text,
  skills text,
  awards text,
  memberships text,
  languages text,
  publications_summary text,
  cv_url text,
  updated_at timestamptz not null default now()
);

alter table public.cv enable row level security;

create policy "Public can read CV"
on public.cv
for select
to anon, authenticated
using (true);

create policy "Authenticated users can insert CV"
on public.cv
for insert
to authenticated
with check (true);

create policy "Authenticated users can update CV"
on public.cv
for update
to authenticated
using (true)
with check (true);

create policy "Authenticated users can delete CV"
on public.cv
for delete
to authenticated
using (true);
