create table public.projects (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  role text,
  status text,
  year integer,
  funding text,
  location text,
  url text,
  image_url text,
  featured boolean not null default false,
  published boolean not null default true,
  created_at timestamptz not null default now()
);

alter table public.projects enable row level security;

create policy "Public can read published projects"
on public.projects
for select
to anon, authenticated
using (published = true);

create policy "Authenticated users can insert projects"
on public.projects
for insert
to authenticated
with check (true);

create policy "Authenticated users can update projects"
on public.projects
for update
to authenticated
using (true)
with check (true);

create policy "Authenticated users can delete projects"
on public.projects
for delete
to authenticated
using (true);