create table public.news (
  id bigint generated by default as identity primary key,
  title text not null,
  excerpt text,
  content text,
  date date not null default current_date,
  category text,
  image_url text,
  url text,
  featured boolean not null default false,
  published boolean not null default true,
  created_at timestamptz not null default now()
);

alter table public.news enable row level security;

create policy "Public can read published news"
on public.news
for select
to anon, authenticated
using (published = true);

create policy "Authenticated users can insert news"
on public.news
for insert
to authenticated
with check (true);

create policy "Authenticated users can update news"
on public.news
for update
to authenticated
using (true)
with check (true);

create policy "Authenticated users can delete news"
on public.news
for delete
to authenticated
using (true);
